---
cf_cli/cf-cli_6.23.1_linux_x86-64.tgz:
  object_id: 6c2e620a-b1f7-4f0e-bf53-f80fa60c403a
  sha: !binary |-
    YTE5NWU5OWNhZTVhYjE3YjQ1M2IwYTA3NDc1MDhjOGYzZWVlNWNhZQ==
  size: 6692717
ecs_service_broker/ecs-cf-service-broker.jar:
  object_id: dec7ebc0-106e-4933-8e3e-cf2aab17ad21
  sha: !binary |-
    YTNiZWNhMTZmZTFjMjg5ZGRjNzBkYzIxNjkyYjJjNGY1MGNmOGM4NQ==
  size: 24201258
